# Generated by Django 2.2.4 on 2024-07-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('credit', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('des', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=255)),
                ('option', models.CharField(max_length=10)),
                ('maxval', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Aution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerprice', models.IntegerField()),
                ('des', models.CharField(max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service')),
            ],
        ),
    ]
