# Generated by Django 2.2.4 on 2024-07-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aution',
            new_name='Auction',
        ),
    ]
