# Generated by Django 3.2.25 on 2024-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240729_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
