# Generated by Django 3.2.25 on 2024-07-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
