# Generated by Django 3.2.25 on 2024-07-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240729_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
