# Generated by Django 3.2.25 on 2024-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_auction_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceend',
            field=models.BooleanField(default=False),
        ),
    ]
