# Generated by Django 3.2.25 on 2024-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service_serviceend'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='usecredit',
            field=models.IntegerField(default=0),
        ),
    ]
